### ISSUE TITLE
[enhancement] マークダウン・imgタグとしての埋め込みへの導線が少しわかりにくいように感じました

### ISSUE THREAD

**Issue by bun913** [koki-develop/badge-generator#1]
## 何を感じたか

とても素敵なサービスありがとうございます！

私だけかもしれませんが、バッジを作った後にマークダウンと出力・imgタグとしての出力までの導線が少しわかりにくく感じましたのでフィードバックです！

以下のようにラベルの方に目がいってしまい、画面右のトグルボタンに気づけず、imgタグの出力ボタンに気づけませんでした。

![スクリーンショット 2022-10-05 21 14 01](https://user-images.githubusercontent.com/73948280/194058068-ee4f5286-1006-4766-90f2-d8ce86c84a9f.png)

## 対策として考えたこと

- 最初から各サービスの一番上のバッジのトグルが開いている状態にする
- 使い方ページ・使い方がわかる説明を設置する
- トグル形式にするのではなく、生成したバッチの横にコピーボタンが表示されるようにする。クリックで「Copy as HTML」のようにポップアップが表示される。（雑で申し訳ないですが、下図をご参照ください）

![スクリーンショット 2022-10-05 21 18 45](https://user-images.githubusercontent.com/73948280/194059176-7c586a57-5988-4fdd-94f3-018b4e8b75da.png)

この機能が分かりやすいことで、初心者の方も使いやすいかなと思ったので挙げさせていただきました！

**Comment by koki-develop** [comment]
@bun913 
すごくご丁寧にフィードバックいただきありがとうございます！
提案までいただいてめっちゃわかりやすくて助かります 🙇‍♂️ 

> ラベルの方に目がいってしまい、画面右のトグルボタンに気づけず

うーむ、たしかに。
特に画面幅が広いほど離れてしまってわかりづらいですね。

いただいた案も参考にさせていただいてちょっと考えてみます、ありがとうございます！

**Comment by koki-develop** [comment]
@bun913 
とりあえずシンプルにトグルボタンを左に持ってきてみました！
視線移動も減るので前よりは気づきやすくなったかなと思います。
![Badge-Generator](https://user-images.githubusercontent.com/47014617/194066278-da4bb62c-350b-46d8-8511-d63ba68ec084.png)

> トグル形式にするのではなく、生成したバッチの横にコピーボタンが表示されるようにする

こちらも結構悩んだのですが、ラベルなどのカスタマイズ用の Input の置き場にちょっと困ってしまうんですよねー、、
バッジの下に置くと各種バッジが専有する高さが広くなってしまう = バッジの一覧性が落ちてしまうのでやはりトグル形式にしてコンパクトにまとめたい、という意図です。

**Comment by koki-develop** [comment]
@bun913 
ありがとうございます！
そうしましたら一旦本件クローズさせていただきます！ 🙆‍♂️ 
また何かありましたらIssueくださいーーー 🙇‍♂️ 🙇‍♂️
